### PR TITLE
neg instruction should add 1 to complimented value

### PR DESCRIPTION
**Pull request by ceyhunsen**

### CODE REVIEW

**Comment by YJDoc2** [comment]
Hey,
Thanks for making a PR!
There are some changes required, will you be willing to make those and update the PR?

**Comment by ceyhunsen** [comment]
I am not that great with Rust but I will do anything I can. What needs to be changed?

**Comment by YJDoc2** [comment]
I think this change will be breaking the original tests, so you will need to update the tests as well. Also in the 8086 manual https://edge.edx.org/c4x/BITSPilani/EEE231/asset/8086_family_Users_Manual_1_.pdf , the Neg instruction specifies some extra constraints/ conditions, which I have also missed. Please check and add those as well.

**Comment by ceyhunsen** [comment]
I think I fixed the test. But right now I don't have time for reading 8086 manual and fix other problems. Also compiling program changed a bunch of lines. I honestly don't know why that happened. All I done is run `cargo test`.

**Comment by YJDoc2** [comment]
Hey

> I think I fixed the test. But right now I don't have time for reading 8086 manual and fix other problems. 

Thanks for that :+1:

> Also compiling program changed a bunch of lines. I honestly don't know why that happened. All I done is run cargo test.

Yes that is not an issue, that happens as the lalrpop generates the parser at build time.

I will merge this in the current state :+1:

Thank you for contributing !

**Pull request merged**
